"""Creating tables

Revision ID: 61feb4d3f437
Revises: 
Create Date: 2022-06-20 18:20:52.804559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61feb4d3f437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_text', sa.Text(), nullable=False),
    sa.Column('id_str', sa.String(length=255), nullable=False),
    sa.Column('user_screen_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_classificators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_classification', sa.Enum('positive', 'negative', 'neutral', name='sentimentclassificationenum'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_classificators')
    op.drop_table('tweets')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
